tasks = [
    {
        "taskId": "RD101",
        "title": "Refactor image cropping component",
        "description": "Update React component to support dual cropping functionality using react-easy-crop.",
        "status": "Completed",
        "start_date": "2024-08-10",
        "end_date": "2024-08-12",
    },
    {
        "taskId": "RD108",
        "title": "Integrate LangChain with OpenAI API",
        "description": "Develop a LangChain agent to process conversational memory using the OpenAI API.",
        "status": "Completed",
        "start_date": "2024-08-14",
        "end_date": "2024-08-15",
    },
    {
        "taskId": "RD109",
        "title": "Write unit tests for smart contract",
        "description": "Implement comprehensive test cases for NFT lifecycle smart contracts.",
        "status": "In Progress",
        "start_date": "2024-08-19",
        "end_date": None,
    },
    {
        "taskId": "RD110",
        "title": "Setup CI/CD pipeline",
        "description": "Establish a continuous integration and deployment pipeline for the NFT project using GitHub Actions.",
        "status": "Pending",
        "start_date": None,
        "end_date": None,
    },
    {
        "taskId": "RD102",
        "title": "Analyze hex-formatted stream lengths",
        "description": "Perform calculations for hex formatting in pixel streams, ensuring correct stream length processing.",
        "status": "Completed",
        "start_date": "2024-08-13",
        "end_date": "2024-08-14",
    },
    {
        "taskId": "RD104",
        "title": "Prepare interview AI prompt",
        "description": "Draft detailed configuration for an AI interviewer to assess candidates for technical roles.",
        "status": "Completed",
        "start_date": "2024-08-16",
        "end_date": "2024-08-17",
    },
    {
        "taskId": "RD105",
        "title": "Implement retrieval-augmented generation pipeline",
        "description": "Set up RAG workflows leveraging vector databases for document retrieval in AI models.",
        "status": "In Progress",
        "start_date": "2024-08-18",
        "end_date": None,
    },
    {
        "taskId": "RD106",
        "title": "Optimize API response time",
        "description": "Improve backend API performance by reducing response time for large data payloads.",
        "status": "Completed",
        "start_date": "2024-08-11",
        "end_date": "2024-08-13",
    },
    {
        "taskId": "RD107",
        "title": "Design task management system architecture",
        "description": "Create a scalable architecture for a developer task management and review system.",
        "status": "Pending",
        "start_date": None,
        "end_date": None,
    }
]
