tasks = [
    {
        "taskId": "RD101",
        "title": "Refactor image cropping component",
        "description": "Update React component to support dual cropping functionality using react-easy-crop.",
        "status": "Completed",
        "start_date": "2024-12-10",
        "end_date": "2024-12-12",
    },
    {
        "taskId": "RD102",
        "title": "Analyze hex-formatted stream lengths",
        "description": "Perform calculations for hex formatting in pixel streams, ensuring correct stream length processing.",
        "status": "Completed",
        "start_date": "2024-12-13",
        "end_date": "2024-12-14",
    },
    {
        "taskId": "RD103",
        "title": "Develop smart contract for NFT lifecycle tracking",
        "description": "Design and implement an NFT standard for tracking the lifecycle of gems, including linking previous states.",
        "status": "In Progress",
        "start_date": "2024-12-15",
        "end_date": None,
    },
    {
        "taskId": "RD104",
        "title": "Prepare interview AI prompt",
        "description": "Draft detailed configuration for an AI interviewer to assess candidates for technical roles.",
        "status": "Completed",
        "start_date": "2024-12-16",
        "end_date": "2024-12-17",
    },
    {
        "taskId": "RD105",
        "title": "Implement retrieval-augmented generation pipeline",
        "description": "Set up RAG workflows leveraging vector databases for document retrieval in AI models.",
        "status": "In Progress",
        "start_date": "2024-12-18",
        "end_date": None,
    },
    {
        "taskId": "RD106",
        "title": "Optimize API response time",
        "description": "Improve backend API performance by reducing response time for large data payloads.",
        "status": "Completed",
        "start_date": "2024-12-11",
        "end_date": "2024-12-13",
    },
    {
        "taskId": "RD107",
        "title": "Design task management system architecture",
        "description": "Create a scalable architecture for a developer task management and review system.",
        "status": "Pending",
        "start_date": None,
        "end_date": None,
    },
]
